upstream api_gateway {
  server gateway:3000;
}

upstream helpdesk_app {
  server helpdesk-saas:3010;
}

upstream analytics_app {
  server analytics-dashboard:3011;
}

upstream admin_app {
  server admin-panel:3012;
}

upstream chat_app {
  server realtime-chat:3014;
}

upstream website_app {
  server website:3013;
}
