export const routes = {
  home: '/',
  dashboard: '/dashboard',
  tickets: '/tickets',
  inbox: '/inbox',
  customers: '/customers',
  knowledgeBase: '/knowledge-base',
  settings: '/settings',
  administration: '/administration',
  analytics: '/analytics',
  profile: '/profile',
  search: '/search',
  notifications: '/notifications',
  login: '/login',
  register: '/register',
  ticketDetail: (id: string) => `/tickets/${id}`,
} as const;
